name: NuGet

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v4
      - uses: NuGet/setup-nuget@v2
      - uses: microsoft/setup-msbuild@v2
      - name: Pack
        run: dotnet pack /Restore /bl /p:Configuration=Release /p:Repository=${{ github.repository_owner }} /p:Version=${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: msbuild.binlog
          path: msbuild.binlog
          retention-days: 1
      - name: NuGet Push
        run: nuget push artifacts\package\release\*.nupkg -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/" -apikey "${{ secrets.GITHUB_TOKEN }}"
